#!/usr/bin/env python3

from utils import *
import pandas as pd
from argparse import ArgumentParser


def get_args():
    parser = ArgumentParser()
    parser.add_argument("-s", "--symbol", dest="symbol",
                          help="the symbol to fetch data for", default="aapl")
    parser.add_argument("-n", "--numdays", dest="days",
                          help="the number of days back", default=1450, type=int)
    args = vars(parser.parse_args())
    return args


def main():
    args = get_args()
    df = get_combined_data(args['symbol'], args['days'])
    df.to_csv(f"./data/{args['symbol']}_compleate_1d.csv")


if __name__ == "__main__":
    main()
